# Generated by Django 4.2.27 on 2025-12-22 23:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя актёра')),
            ],
            options={
                'verbose_name': 'Актёр',
                'verbose_name_plural': 'Актёры',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('year', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1888), django.core.validators.MaxValueValidator(2025)], verbose_name='Год выпуска')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='ads/', verbose_name='Постер')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('director', models.CharField(max_length=100, verbose_name='Режиссёр')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='В топ-5')),
                ('actors', models.ManyToManyField(blank=True, to='ads.actor', verbose_name='Актёры')),
            ],
            options={
                'verbose_name': 'Фильм',
                'verbose_name_plural': 'Фильмы',
                'ordering': ['-year'],
            },
        ),
    ]
